# Site settings
title: Christopher Wells
email: cwells2@oswego.edu
baseurl: "http://www.cs.oswego.edu/~cwells2"
url: "http://www.cs.oswego.edu/~cwells2"

# Build settings
markdown: kramdown

# Ignore unwanted files
exclude:
  - Gemfile
  - Rakefile
  - Makefile
